FROM tensorflow/tensorflow:latest-gpu
WORKDIR /app/backend

RUN pip install --upgrade pip
COPY backend/requirements_trainer.txt requirements_trainer.txt
RUN pip install -r requirements_trainer.txt

COPY backend .
