# Generated by Django 3.2 on 2022-09-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaic', '0016_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pvdata',
            old_name='irradiation',
            new_name='irradiance',
        ),
    ]
