# Generated by Django 3.2 on 2022-11-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaic', '0018_aialgorithm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertTreshold',
            new_name='AlertThreshold',
        ),
        migrations.RenameField(
            model_name='alertthreshold',
            old_name='treshold_ft_max',
            new_name='threshold_ft_max',
        ),
        migrations.RenameField(
            model_name='alertthreshold',
            old_name='treshold_ft_min',
            new_name='threshold_ft_min',
        ),
        migrations.RenameField(
            model_name='alertthreshold',
            old_name='treshold_wa_max',
            new_name='threshold_wa_max',
        ),
        migrations.RenameField(
            model_name='alertthreshold',
            old_name='treshold_wa_min',
            new_name='threshold_wa_min',
        ),
    ]
